version: 0.0
os: linux
files:
  - source: /
    destination: /home/django-api/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
