version: '3.8'

services:
  api:
    # Pulls the latest built image from your AWS ECR
    image: 559307249825.dkr.ecr.ap-south-1.amazonaws.com/django-api:latest
    container_name: django_backend
    restart: always

    environment:
      - AWS_REGION=ap-south-1
      - SECRET_NAME=breathline/db-credentials
      - PYTHONUNBUFFERED=1
      - STATIC_ROOT=/srv/staticfiles
      - DJANGO_SETTINGS_MODULE=breathline.settings
      - PYTHONPATH=/app

    ports:
      - "80:8000"

    volumes:
      # Persistent storage for CSS, JS, and Images
      - static_content:/srv/staticfiles
      - ./apply_patch.sh:/app/apply_patch.sh
      - ./custom_migrations:/app/custom_migrations
      - ./patch_settings.py:/app/breathline/local_settings.py

    # COMMAND OVERRIDE: 
    # This bypasses entrypoint.sh to ensure 'makemigrations' is NEVER called.
    # It runs migrate, then starts the production server.
    command: >
      sh -c "./apply_patch.sh && python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn breathline.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"

volumes:
  static_content:
