version: '3.8'

services:
  api:
    build: .
    container_name: django_backend
    restart: always

    environment:
      - AWS_REGION=ap-south-1
      - SECRET_NAME=breathline/db-credentials
      - PYTHONUNBUFFERED=1

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - static_content:/app/static

    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]

volumes:
  static_content:
