# Generated by Django 5.0.2 on 2026-03-11 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_role_permission_label_permission_sub_label'),
        ('django_acl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='modified_date')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='username')),
                ('password', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='password')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last_login')),
                ('last_logout', models.DateTimeField(blank=True, null=True, verbose_name='last_logout')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='last_active')),
                ('last_password_reset', models.DateTimeField(blank=True, null=True, verbose_name='last_password_reset')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('failed_login_attempts', models.IntegerField(blank=True, null=True, verbose_name='Failed Login Attempts')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_password_already_updated', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Password Already Updated')),
                ('is_invited_by_admin', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Invited By Admin')),
                ('is_password_reset_required', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('first_name', models.CharField(blank=True, max_length=225, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=225, null=True, verbose_name='last_name')),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Profile Image')),
                ('replica_db', models.CharField(blank=True, choices=[('replica_1', 'Replica 1'), ('replica_2', 'Replica 2')], max_length=20, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone Number')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', null=True, verbose_name='Gender')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', related_query_name='user', to='django_acl.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='modified_date')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('error_message', models.TextField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
            },
        ),
        migrations.CreateModel(
            name='GeneratedAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='modified_date')),
                ('token', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
